name: StoneDrop
main: domcie.stonedrop
version: 0.1
author: DomCie99
commands:
  drop:
    description: Drop menu
  turbodrop:
    description: Turbodrop for player
  cobble: 
    description: ON/OFF Cobblestone
  cobblestone: 
    description: ON/OFF Cobblestone
